### ISSUE TITLE
Binary distribution, no source... do you actually expect anyone to run this?

### ISSUE THREAD

**Issue by justinh-rahb** [ianand/spreadsheets-are-all-you-need#7]
Mmmmm mystery meat

**Comment by marke-apexit** [comment]
@justinh-rahb I was able to download the spreadsheet and open it, everything is in there.  The readm

**Comment by ianand** [comment]
@justinh-rahb Is your concern the lack of source code (i.e. transparency in how it is implemented) or safety (i.e. potential exposure to viruses, etc.)

Re: the lack of source code (i.e. transparency in how it is implemented). All the implementation is in the file and viewable in Excel. It's unfortunate that this requires Excel but am looking into alternatives (see https://github.com/ianand/spreadsheets-are-all-you-need/issues/2). If there's another format you're aware of that compiles into an Excel file, please let me know.

Re: safety (i.e. potential exposure to viruses, etc.). I understand this concern. However, this file does not use any macros as evidenced from the file extension (see https://superuser.com/questions/642419/how-can-you-find-out-if-xlsx-and-docx-files-are-safe-to-open). You can also open it in Protected View (see https://support.microsoft.com/en-au/office/what-is-protected-view-d6f09ac7-e6b9-4495-8e43-2bbcdbcb6653)

**Comment by justinh-rahb** [comment]
Appreciate your reasoned response @ianand. If I might make a suggestion, that may be a good thing to put in the README.

**Comment by ianand** [comment]
Thanks. Re-opening so I remember to add to the website and readme.

**Comment by ianand** [comment]
Note to self: I was wrong. While XLSX can't contain macros, XLSB can.

**Comment by fakerybakery** [comment]
Hi @ianand, this is super cool! Just curious why you chose XLSB instead of XLSX?

**Comment by marke-apexit** [comment]
I'm not answering for the project, but XLSB files are smaller than XLSX especially for a spreadsheet filled with so many value constants (weights, biases, vectors).
